### PR TITLE
Changed target 2.1 to 5.0

### PR DESCRIPTION
**Pull request by v-gpettibone**
## Purpose
Make the QuickStart sample run with net 5.0
* ...

## Does this introduce a breaking change?
Don't know
```
[ ] Yes
[ ] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code
Run the QuickStart
```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by v-gpettibone** [comment]
@robinsh  Made code change from target 2.1.0 to target net5.0. Necessary to get QS to run.

**Comment by robinsh** [comment]
What does it mean “necessary to get qs to run” ?

**Comment by v-gpettibone** [comment]
The QuickStart targeted the 2.1.0 SDK. It needs to target 3.1 or later in order to run. Hence, changed to 5 which is, I believe, the latest.

Greg

**Comment by robinsh** [comment]
Oh, ok. So does it work now?

**Comment by v-gpettibone** [comment]
Yes, that was the only change necessary to get it to run.

Greg

**Comment by drwill-ms** [comment]
I already have this change in a PR under review: https://github.com/Azure-Samples/azure-iot-samples-csharp/pull/167

**Comment by v-gpettibone** [comment]
Taken care of by the product team's commits

**Pull request closed without merging**
