### PR TITLE
Avoid clearing s_telemetryInterval when an invalid parameter is received

### PR DESCRIPTION
**Pull request by tony-xia**
## Purpose
In current implementation, when an invalid parameter is received, the internal will be reset to be zero, which makes the simulated device send message to cloud very fast.
* ...

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* ...

### CODE REVIEW

**Comment by tony-xia** [comment]
any update？

**Comment by CIPop** [comment]
Sorry @tony-xia for the very late reply. We'll run this through our automation and merge if it passes.

**Comment by bikamani** [comment]
@tony-xia Thank you for contribution. This is not relevant anymore and hence closing this PR.

**Pull request closed without merging**
