### PR TITLE
add comment about sleep command

### PR DESCRIPTION
**Pull request by robinsh**
Add comments explaining why there's a wait-sleep command in the powershell code here
so the user doesn't remove it, not thinking they need it.

### CODE REVIEW

**Comment by robinsh** [comment]
wait until it finishes building, then can send request to get this merged to master.

**Comment by robinsh** [comment]
when this builds successfully, can sign off on it

**Comment by robinsh** [comment]
#sign-off

**Comment by robinsh** [comment]
#sign-off

**Review by drwill-ms — APPROVED** [review]

**Pull request merged**
